version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: spring-api-db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks:
      - m1guelsb-network
  spring-api:
    image: m1guelsb/spring-api
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-db:3306/spring-api-db
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - '8080:8080'
    command: mvn spring-boot:run
    depends_on:
      - mysql-db
    networks:
      - m1guelsb-network

networks:
  m1guelsb-network:
    driver: bridge