
name: Continuous Integration with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{  secrets.DOCKER_USERNAME  }}
        password: ${{  secrets.DOCKER_PASSWORD  }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      run: mvn clean package

    - name: Docker Compose Build
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker pull m1guelsb/spring-api:latest
        
        docker tag ${{  secrets.DOCKER_USERNAME  }}/spring-api ${{  secrets.DOCKER_USERNAME  }}/spring-api:${{  github.run_id  }}

        docker push ${{  secrets.DOCKER_USERNAME  }}/spring-api:${{  github.run_id  }}
        docker push ${{  secrets.DOCKER_USERNAME  }}/spring-api
